"""initial

Revision ID: 2e1372c52c2f
Revises: 
Create Date: 2026-09-27 13:01:04.212369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e1372c52c2f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=25), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_table('geofences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('geofence_type', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_geofences_geometry', 'geofences', ['geometry'], unique=False, postgresql_using='gist')
    op.create_table('worker_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_code', sa.String(length=25), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_code')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=25), nullable=False),
    sa.Column('plate', sa.String(length=25), nullable=False),
    sa.Column('brand', sa.String(length=55), nullable=False),
    sa.Column('model', sa.String(length=55), nullable=False),
    sa.Column('vehicle_type', sa.String(length=55), nullable=False),
    sa.Column('engine_type', sa.String(length=55), nullable=False),
    sa.Column('odometer', sa.Float(), nullable=True),
    sa.Column('last_address', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate')
    )
    op.create_index('uq_one_active_vehicle_per_device', 'vehicles', ['device_id'], unique=True, postgresql_where=sa.text('end_date IS NULL'))
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.Column('last_name', sa.String(length=55), nullable=False),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('dni', sa.String(length=10), nullable=False),
    sa.Column('worker_code_id', sa.String(length=25), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['worker_code_id'], ['worker_code.worker_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('phone')
    )
    op.create_index('uq_one_active_worker_per_worker_code', 'workers', ['worker_code_id'], unique=True, postgresql_where=sa.text('end_date IS NULL'))
    op.create_table('usage_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=25), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'FINISHED', name='statusenum'), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('start_odometer', sa.Float(), nullable=False),
    sa.Column('start_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('trip_purpose', sa.String(length=500), nullable=True),
    sa.Column('pre_check_notes', sa.Text(), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_odometer', sa.Float(), nullable=True),
    sa.Column('end_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('total_km', sa.Float(), nullable=True),
    sa.Column('total_seconds', sa.Integer(), nullable=True),
    sa.Column('end_reason', sa.Enum('GEOFENCE', 'MANUAL', 'TIMEOUT', name='endreason'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_sessions_end_location', 'usage_sessions', ['end_location'], unique=False, postgresql_using='gist')
    op.create_index('idx_usage_sessions_start_location', 'usage_sessions', ['start_location'], unique=False, postgresql_using='gist')
    op.create_index('uq_one_active_sesion_per_vehicle_id', 'usage_sessions', ['vehicle_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('vehicle_geofences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('geofence_id', sa.Integer(), nullable=False),
    sa.Column('alert_on_enter', sa.Boolean(), nullable=False),
    sa.Column('alert_on_exit', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['geofence_id'], ['geofences.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id', 'geofence_id', name='uq_vehicle_geofence')
    )
    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=25), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('alt', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('course', sa.Float(), nullable=True),
    sa.Column('sats', sa.Integer(), nullable=True),
    sa.Column('hdop', sa.Float(), nullable=True),
    sa.Column('ignition', sa.Boolean(), nullable=False),
    sa.Column('aspa_active', sa.Boolean(), nullable=False),
    sa.Column('battery_voltage', sa.Float(), nullable=True),
    sa.Column('battery_current_ma', sa.Float(), nullable=True),
    sa.Column('alert', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['usage_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_telemetry_location', 'telemetry', ['location'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_telemetry_location', table_name='telemetry', postgresql_using='gist')
    op.drop_table('telemetry')
    op.drop_table('vehicle_geofences')
    op.drop_index('uq_one_active_sesion_per_vehicle_id', table_name='usage_sessions', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index('idx_usage_sessions_start_location', table_name='usage_sessions', postgresql_using='gist')
    op.drop_index('idx_usage_sessions_end_location', table_name='usage_sessions', postgresql_using='gist')
    op.drop_table('usage_sessions')
    op.drop_index('uq_one_active_worker_per_worker_code', table_name='workers', postgresql_where=sa.text('end_date IS NULL'))
    op.drop_table('workers')
    op.drop_index('uq_one_active_vehicle_per_device', table_name='vehicles', postgresql_where=sa.text('end_date IS NULL'))
    op.drop_table('vehicles')
    op.drop_table('worker_code')
    op.drop_index('idx_geofences_geometry', table_name='geofences', postgresql_using='gist')
    op.drop_table('geofences')
    op.drop_table('devices')
    # ### end Alembic commands ###
