"""Change FK workers -> workers_code

Revision ID: 34a00c6420c2
Revises: f933163ee328
Create Date: 2026-09-19 11:25:26.463802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '34a00c6420c2'
down_revision: Union[str, Sequence[str], None] = 'f933163ee328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('workers_worker_code_id_fkey'), 'workers', type_='foreignkey')
    op.alter_column('workers', 'worker_code_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=25),
               existing_nullable=False)
    op.create_foreign_key(None, 'workers', 'worker_code', ['worker_code_id'], ['worker_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workers', type_='foreignkey')
    op.create_foreign_key(op.f('workers_worker_code_id_fkey'), 'workers', 'worker_code', ['worker_code_id'], ['id'])
    op.alter_column('workers', 'worker_code_id',
               existing_type=sa.String(length=25),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
