"""add geofences and vehicle_geofences

Revision ID: 365bd49e78fa
Revises: e75259ea4c4c
Create Date: 2026-09-18 08:47:23.283366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '365bd49e78fa'
down_revision: Union[str, Sequence[str], None] = 'e75259ea4c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
