"""add vehicle worker device usage_sessions

Revision ID: 7b6cb9e7e95c
Revises: a8dc2d23893c
Create Date: 2026-09-17 09:35:01.186615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '7b6cb9e7e95c'
down_revision: Union[str, Sequence[str], None] = 'a8dc2d23893c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_code', sa.String(length=25), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_code')
    )
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.Column('last_name', sa.String(length=55), nullable=False),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('dni', sa.String(length=10), nullable=False),
    sa.Column('worker_code_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['worker_code_id'], ['worker_code.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('phone')
    )
    op.create_index('uq_one_active_worker_per_worker_code', 'workers', ['worker_code_id'], unique=True, postgresql_where=sa.text('end_date IS NULL'))
    op.create_table('usage_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=25), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'FINISHED', name='statusenum'), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('start_odometer', sa.Float(), nullable=False),
    sa.Column('start_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('trip_purpose', sa.String(length=500), nullable=True),
    sa.Column('pre_check_notes', sa.Text(), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_odometer', sa.Float(), nullable=True),
    sa.Column('end_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('total_km', sa.Float(), nullable=True),
    sa.Column('total_seconds', sa.Integer(), nullable=True),
    sa.Column('end_reason', sa.Enum('GEOFENCE', 'MANUAL', 'TIMEOUT', name='endreason'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
  
    op.create_index('uq_one_active_sesion_per_vehicle_id', 'usage_sessions', ['vehicle_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.add_column('telemetry', sa.Column('session_id', sa.Integer(), nullable=True))
    op.alter_column('telemetry', 'sats',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(None, 'telemetry', 'usage_sessions', ['session_id'], ['id'])
    op.create_index('uq_one_active_vehicle_per_device', 'vehicles', ['device_id'], unique=True, postgresql_where=sa.text('end_date IS NULL'))
    op.drop_column('vehicles', 'driver')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('driver', sa.VARCHAR(length=55), autoincrement=False, nullable=True))
    op.drop_index('uq_one_active_vehicle_per_device', table_name='vehicles', postgresql_where=sa.text('end_date IS NULL'))
    op.drop_constraint(None, 'telemetry', type_='foreignkey')
    op.alter_column('telemetry', 'sats',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('telemetry', 'session_id')
    op.drop_index('uq_one_active_sesion_per_vehicle_id', table_name='usage_sessions', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_table('usage_sessions')
    op.drop_index('uq_one_active_worker_per_worker_code', table_name='workers', postgresql_where=sa.text('end_date IS NULL'))
    op.drop_table('workers')
    op.drop_table('worker_code')
    # ### end Alembic commands ###
