"""add vehicles table

Revision ID: 9efbfeeaa4c5
Revises: f8e2ed9a9e37
Create Date: 2026-08-29 19:52:16.808418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9efbfeeaa4c5'
down_revision: Union[str, Sequence[str], None] = 'f8e2ed9a9e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
