"""add aspa_active battery alert fields

Revision ID: f8e2ed9a9e37
Revises: 68fcb6b92052
Create Date: 2026-08-18 06:50:12.642593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e2ed9a9e37'
down_revision: Union[str, Sequence[str], None] = '68fcb6b92052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
