"""add odometer in vehicles model and schemas

Revision ID: f933163ee328
Revises: e5aadd85080c
Create Date: 2026-09-18 09:23:02.297369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f933163ee328'
down_revision: Union[str, Sequence[str], None] = 'e5aadd85080c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('odometer', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'odometer')
    # ### end Alembic commands ###
